Added Labels for Issue Template
EddieHubCommunity/support pull request #1327
Opened 2021-04-19 17:24 UTC by Prathamesh-Shanbhag

closes: 1/4 #1325

#### What does this PR do?
Adds Livestream Label to Github Profile Review
#### Description of Task to be completed?

#### How can this be manually tested?

#### Any background context you want to provide?

#### What is the relevant issue link?
https://github.com/EddieHubCommunity/support/issues/1325

#### Screenshots (if appropriate)

#### Questions:

2021-04-19 17:28 UTC, nhcarrigan requested changes

2021-04-19 17:28 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/gh-profile-review.md
> +labels: gh profile review, live stream review'
```suggestion
labels: 'gh profile review, live stream review'
```

Missing the opening quote. :)

2021-04-20 19:29 UTC, schmelto approved these changes
With @nhcarrigan changes it looks good for me

2021-04-23 21:18 UTC, nhcarrigan commented
@Prathamesh-Shanbhag could you commit the suggestion above?

2021-04-23 23:51 UTC, Prathamesh-Shanbhag commented
> @Prathamesh-Shanbhag could you commit the suggestion above?

Done nick!

2021-04-24 02:44 UTC, schmelto approved these changes

2021-04-24 15:14 UTC, nhcarrigan approved these changes
Looks good to me!

2021-04-24 15:14 UTC, merged