[feat/fix]: Minor improvements in the YouTube description file
EddieHubCommunity/support pull request #2203
Opened 2021-08-15 16:51 UTC by Panquesito7

#### What does this PR do?

- Improves the YouTube `review.md` file.
  - Removed Markdown stuff such as headers. Other minor improvements are shown in the Git diff.

#### Description of the task to be completed?

None.

#### How can this be manually tested?

I don't think this applies here.

#### Any background context you want to provide?

Nope.

#### Is there any relevant issue to this PR?

#2202

#### Questions

None.

2021-08-15 17:12 UTC, schmelto requested changes

2021-08-15 17:12 UTC, schmelto commented on youtube/reviews.md
> +https://discord.eddiehub.org/
```suggestion
http://discord.eddiehub.org/
```
Https isn't working on this link

2021-08-15 17:12 UTC, schmelto commented on youtube/reviews.md
> +Follow on other socials for behind the scenes footage. Join the Discord server to continue the conversation.
```suggestion
Follow on other socials for behind the scenes footage and join the Discord server to continue the conversation.
```
For me this sounds better but you don't have to commit this.

2021-08-15 18:14 UTC, schmelto approved these changes
Lgtm

@eddiejaoude maybe you should also take a look here

2021-08-16 03:00 UTC, krishdevdb approved these changes

2021-08-16 03:01 UTC, krishdevdb commented
Well, merging this pr makes an issue open, we need to be consistent so we shall also change the other files? This is a good first issue for someone. (Open an issue, then you might also open a pr)...

2021-08-16 03:34 UTC, KukretiShubham approved these changes

2021-08-16 03:36 UTC, KukretiShubham commented
LGTM👍

2021-08-16 05:24 UTC, eddiejaoude approved these changes
LGTM

2021-08-16 05:25 UTC, eddiejaoude commented
Thank you all 👍 great collaboration 💥

2021-08-16 05:25 UTC, merged