Fixed eddiebot broken readme link
EddieHubCommunity/support pull request #3023
Opened 2021-11-29 18:33 UTC by pranv-sonawane

closes #ISSUE-YES

#### What does this PR do?
this fixes the broken link found in the support readme section for Open source tips from EddieBot
#### Description of the task to be completed?
the link has been modified 
#### How can this be manually tested?

#### Any background context you want to provide?

#### Is there any relevant issue to this PR?

#### Screenshots (if appropriate)

#### Questions

2021-11-29 19:04 UTC, Panquesito7 approved these changes

2021-11-29 19:43 UTC, schmelto commented on README.md
> +- **How to look for an open-source project to contribute?** Check [Finding Open Source Projects](https://github.com/EddieHubCommunity/support/blob/main/docs/tips/finding-open-source-projects.md)
```suggestion
- **How to look for an open-source project to contribute?** Check [Finding Open Source Projects](./docs/tips/finding-open-source-projects.md)
```

2021-11-29 19:44 UTC, schmelto commented
Could you add the issue number in the pr description with for example `resolve #123 `

2021-11-29 19:45 UTC, schmelto commented on README.md
> +- **How to look for an open-source project to contribute?** Check [Finding Open Source Projects](https://github.com/EddieHubCommunity/support/blob/main/docs/tips/finding-open-source-projects.md)
I suggest using this annotation

2021-11-30 03:05 UTC, krishguptadev submitted a review, later dismissed
Just @schmelto's suggestions and then 🚀

2021-11-30 09:18 UTC, pranv-sonawane commented on README.md
> +- **How to look for an open-source project to contribute?** Check [Finding Open Source Projects](https://github.com/EddieHubCommunity/support/blob/main/docs/tips/finding-open-source-projects.md)
hi @schmelto i did another pr for that

2021-11-30 09:29 UTC, schmelto commented on README.md
> +  - [Open source tips from EddieBot](https://github.com/EddieHubCommunity/support/tree/main/docs/tips)
```suggestion
  - [Open source tips from EddieBot](./docs/tips)
```

2021-11-30 15:58 UTC, Panquesito7 requested changes
Please see the comments above.

2021-12-01 09:56 UTC, schmelto approved these changes

2021-12-01 12:47 UTC, krishguptadev approved these changes

2021-12-01 16:51 UTC, Panquesito7 approved these changes

2021-12-05 00:34 UTC, nhcarrigan requested changes
Am I missing something? This appears to be a duplicate of #3021?

2021-12-05 06:38 UTC, krishguptadev commented
Yes its a duplicate 🤔

2021-12-05 12:44 UTC, nhcarrigan commented
Hey there,

Thanks for your interest in contributing. However this appears to be a duplicate of your previous pull request - as such, we are unable to accept these changes.

We encourage you to continue contributing by looking for issues labelled `help wanted`!

2021-12-05 12:44 UTC, closed without merging