Feat new theme
EddieHubCommunity/support pull request #3040
Opened 2021-12-02 08:16 UTC by krishguptadev

closes #ISSUE-NO

#### What does this PR do?

Adds a new theme, navbar and sidebar

#### Description of the task to be completed?

- [x] Theme
- [x] Navbar
- [x] Sidebar 

#### How can this be manually tested?

- [ ] Deployed to [gh-pages]

#### Any background context you want to provide?

We can then customize the theme [using the available options](https://docsify-darklight-theme.boopathikumar.me/#/configuration?id=default-themes-configuration)

#### Is there any relevant issue to this PR?

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/91655303/144383544-9da8a4ff-6dbf-42eb-8278-3d505a3a8290.png)

#### Questions

2021-12-02 09:16 UTC, schmelto approved these changes

2021-12-03 18:14 UTC, Panquesito7 requested changes

2021-12-03 18:14 UTC, Panquesito7 commented on docs/_layout/navbar.md
> +- [Youtube](https://youtube.com/c/eddiejaoude)
```suggestion
- [YouTube](https://youtube.com/c/eddiejaoude)
```

2021-12-03 18:14 UTC, Panquesito7 commented on docs/_layout/sidebar.md
> +  - [Youtube Generic Template](/youtube/generic.md)
```suggestion
  - [YouTube Generic Template](/youtube/generic.md)
```

2021-12-03 18:14 UTC, Panquesito7 commented on docs/index.html
> +</html>
Missing an endline.
```suggestion
</html>

```

2021-12-05 00:30 UTC, nhcarrigan requested changes
The existing theme specifically used colours indicated in the branding repository. The new theme should do the same.

2021-12-05 06:41 UTC, krishguptadev commented
Okey! I'll work on that.

2021-12-07 16:46 UTC, Vyvy-vi reviewed
looks good, though the navbar is kinda unnecessary and leads to too much noise in the top right corner - 
![Screenshot 2021-12-07 at 10 08 47 PM](https://user-images.githubusercontent.com/62864373/145069712-76a46384-bc55-4965-a9cf-6458c1bf9166.png)

2021-12-07 17:26 UTC, Panquesito7 commented on docs/index.html
> +</html>
I think this needs an endline? 😅
```suggestion
</html>

```

2021-12-08 02:38 UTC, krishguptadev commented
> looks good, though the navbar is kinda unnecessary and leads to too much noise in the top right corner - ![Screenshot 2021-12-07 at 10 08 47 PM](https://user-images.githubusercontent.com/62864373/145069712-76a46384-bc55-4965-a9cf-6458c1bf9166.png)

I am not sure, but IMHO the links to discord and sutff should not be in sidebar that is why I added the here

2021-12-08 03:07 UTC, Panquesito7 commented on docs/index.html
> +    repo: "eddiehubcommunity/support",
```suggestion
    repo: "EddieHubCommunity/support",
```

2021-12-08 03:07 UTC, Panquesito7 commented
We could also look into adding a favicon. It would look better. 🙂

2021-12-08 03:27 UTC, krishguptadev commented
> We could also look into adding a favicon. It would look better. 🙂

Not the purpose of the PR. Will add it in another one though 🙂

2021-12-23 22:07 UTC, ezeamaka2 commented
Been trying to create a pull request, so I can request access to join this amazing community. Please someone should add me

2021-12-24 02:25 UTC, krishguptadev commented
> Been trying to create a pull request, so I can request access to join this amazing community. Please someone should add me

You need to create an Issue: https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization

2021-12-24 05:50 UTC, ezeamaka2 commented
> > Been trying to create a pull request, so I can request access to join this amazing community. Please someone should add me
> 
> You need to create an Issue: https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization

Oh, thanks

2022-01-24 20:43 UTC, nhcarrigan approved these changes
Let's go ahead and get this in.

2022-01-24 20:43 UTC, merged