Make Discord and Youtube lniks more concise in README
EddieHubCommunity/support pull request #3940
Opened 2022-05-12 18:54 UTC by karthikmurali60

closes https://github.com/EddieHubCommunity/support/issues/3686

#### What does this PR do?
This PR makes the Discord and Youtube links more concise in the README file

#### Description of the task to be completed?

#### How can this be manually tested?

#### Any background context you want to provide?

#### Is there any relevant issue to this PR?
https://github.com/EddieHubCommunity/support/issues/3686

#### Screenshots (if appropriate)

#### Questions

2022-05-12 19:59 UTC, TheRemyD approved these changes
Links look great

2022-05-13 06:39 UTC, schmelto reviewed
Maybe this as small suggestion but not really needed I leave it to you if you want this styling change

2022-05-13 06:39 UTC, schmelto commented on README.md
> +Join our [Discord](http://discord.eddiehub.org) community
```suggestion
Join our [Discord community](http://discord.eddiehub.org)   
```

2022-05-13 06:39 UTC, schmelto commented on README.md
> +Subscribe to our [YouTube](https://www.youtube.com/user/eddiejaoude) channel
```suggestion
Subscribe to our [YouTube channel](https://www.youtube.com/user/eddiejaoude)
```

2022-05-16 16:55 UTC, FahimFBA requested changes

2022-05-16 16:55 UTC, FahimFBA commented on README.md
> +Join our [Discord](http://discord.eddiehub.org) community
```suggestion
Join our [Discord community](http://discord.eddiehub.org).
```

2022-05-16 16:55 UTC, FahimFBA commented on README.md
> +Subscribe to our [YouTube](https://www.youtube.com/user/eddiejaoude) channel
```suggestion
Subscribe to our [YouTube channel](https://www.youtube.com/user/eddiejaoude).
```

2022-05-16 16:56 UTC, FahimFBA commented
Also, please correct the PR title.

```diff
- Make Discord and Youtube lniks more concise in README
+ Make Discord and Youtube links more concise in README
```

2022-05-18 05:26 UTC, schmelto approved these changes
## Looking good to me

Your suggested changes looking good to me.
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-05-18 10:44 UTC, FahimFBA approved these changes

2022-05-18 10:45 UTC, FahimFBA commented
Everything looks perfect now.

2022-06-23 19:57 UTC, stemount commented
Closing as there's PR duplication and this is an addition - nothing wrong with the changes! They are just not links right down at the bottom of the README.

2022-06-23 19:57 UTC, closed without merging