fix: unique name
EddieHubCommunity/support pull request #4068
Opened 2022-06-03 08:41 UTC by eddiejaoude

closes #ISSUE-NO

#### What does this PR do?

#### Description of the task to be completed?

#### How can this be manually tested?

#### Any background context you want to provide?

#### Is there any relevant issue to this PR?

#### Screenshots (if appropriate)

#### Questions

2022-06-03 10:48 UTC, kb-s requested changes

2022-06-03 10:48 UTC, kb-s commented on .github/ISSUE_TEMPLATE/add-api-user.yml
> +name: EddieHub API add
can we write it as **"name:  add EddieHub API"**

2022-06-03 18:44 UTC, vijay-jaisankar reviewed
In my opinion, `Eddiehub API` is an apt name for this operation if we treat it to be the most atomic operation possible.

If there is scope for similar operations in the future, naming this something like `Add User to Eddiehub API` would make more sense.

2022-06-03 21:33 UTC, eddiejaoude commented
Yes we have a delete template now too, so we needed to be more specific as there was a name clash

2022-06-04 11:59 UTC, krshkodes requested changes

2022-06-04 11:59 UTC, krshkodes commented on .github/ISSUE_TEMPLATE/add-api-user.yml
> +name: EddieHub API add
I would suggest this 🤔 

```suggestion
name: Get Added to the EddieHub API
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-04 12:03 UTC, bishtanuj approved these changes

2022-06-04 13:08 UTC, schmelto approved these changes
## Looking good to me

Your suggested changes looking good to me.
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-06-04 22:42 UTC, vijay-jaisankar approved these changes

2022-06-04 22:49 UTC, merged

2022-06-08 08:24 UTC, kb-s commented
# Looking good to me 
@krshkodes *your suggestion is awesome*

2022-06-08 08:26 UTC, kb-s commented
*Thanks @vijay-jaisankar for reviewing it*