Update resume-review.md
EddieHubCommunity/support pull request #895
Opened 2021-02-08 11:32 UTC by chryzcodez

2021-02-08 16:57 UTC, SashoStoichkov requested changes
Looks good 👍🏻

2021-02-08 16:57 UTC, SashoStoichkov commented on .github/ISSUE_TEMPLATE/resume-review.md
> +Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)
Here it should be `EddieHub` only

2021-02-12 15:31 UTC, schmelto commented on .github/ISSUE_TEMPLATE/resume-review.md
> +Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)
No that is correct

2021-02-12 15:31 UTC, schmelto approved these changes
Lgtm

2021-02-12 18:35 UTC, AllanRegush commented
@eddiejaoude Should we use EddieHub or EddieHubCommunity?

2021-02-16 23:31 UTC, eddiejaoude commented
Good questions. I am on the fence. Either way, it is better than what it is now. We can always tweak it again if we need. Currently it is definitely wrong with the invalid name and url.

2021-02-16 23:31 UTC, eddiejaoude approved these changes
Thanks 👍

2021-02-16 23:31 UTC, merged