Fixing some links
EddieHubCommunity/support pull request #962
Opened 2021-02-21 13:31 UTC by TawfikYasser

closes #961

#### What does this PR do?

Replace old community link to new

#### Description of Task to be completed?

#### How can this be manually tested?

#### Any background context you want to provide?

#### What is the relevant issue link?

#### Screenshots (if appropriate)

#### Questions:

2021-02-21 14:54 UTC, Nitesh-thapliyal submitted a review, later dismissed

2021-02-21 16:47 UTC, SashoStoichkov requested changes
@TawfikYasser, thank you for the PR 🎉 

The name of the community is just `EddieHub` 🤓 
Here I suggest some changes ⬇️

2021-02-21 16:47 UTC, SashoStoichkov commented on Finding-Open-Source-Projects.md
> +- Look at our projects in the [Eddie Hub Community](https://github.com/EddieHubCommunity) GitHub organization.
`[EddieHub](https://github.com/EddieHubCommunity)`

2021-02-21 16:47 UTC, SashoStoichkov commented on README.md
> +Raise an issue to join the EddieHubCommunity GitHub community.
`Raise an issue to join the EddieHub GitHub community.`

2021-02-21 16:47 UTC, SashoStoichkov commented on README.md
> +      Feel free to check out other cool repositories of EddieHub Community
`EddieHub` ~~Community~~

2021-02-21 16:47 UTC, SashoStoichkov commented on README.md
> +- **What is a GitHub Organization?** Essentially it's a way to group many repositories in an entity called an organization. An organization also allows us to group people who contribute and are a par
`[EddieHub](https://github.com/EddieHubCommunity)`

2021-02-22 12:47 UTC, TawfikYasser commented
I think now required changes are done. @SashoStoichkov

2021-02-22 13:49 UTC, SashoStoichkov commented
LGTM 👍🏻 Thank you for the changes 💯

2021-02-22 13:50 UTC, SashoStoichkov approved these changes
LGTM 👍🏻 Thank you for the changes 💯

2021-02-22 15:48 UTC, galahad42 approved these changes
LGTM!

2021-02-23 02:41 UTC, AllanRegush approved these changes
Looks Good :+1:

2021-02-23 02:41 UTC, AllanRegush commented
Good Work Everyone :tada:

2021-02-23 02:41 UTC, merged

2021-02-28 00:02 UTC, eddiejaoude commented
Great team work everyone 👍 thank you 🤓