Update community.yml
EddieHubCommunity/support pull request #980
Opened 2021-02-25 03:37 UTC by muthuannamalai12

closes #ISSUE-NO
#979 
#### What does this PR do?
Updated Community.yml file 
#### Description of Task to be completed?
I have updated the issue-message, Pr-Message, and footer with new ones in Community.yml
#### How can this be manually tested?
This has been self-tested by me.
#### What is the relevant issue link?
https://github.com/EddieHubCommunity/support/issues/979

2021-02-25 10:57 UTC, schmelto approved these changes

2021-03-02 11:14 UTC, vinzvinci requested changes
What is better to call?

> Discord `chat` or Discord `server`?

2021-03-02 11:16 UTC, Vyvy-vi commented
Discord server might be a better terminology 🤔

2021-03-02 11:45 UTC, DevCassie commented
> Discord server might be a better terminology 🤔

Agreed.

2021-03-02 23:54 UTC, eddiejaoude commented on .github/workflows/community.yml
> +          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.github.org">Disco
Url is incorrect, here is the fix

```suggestion
          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.eddiehub.org">Discord</a> server and our <a href="http://github.eddiehub.org">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.'
```

2021-03-03 11:25 UTC, Vyvy-vi approved these changes
lgtm, but maybe we can hyperlink `Discord server` for more consistency?

2021-03-03 11:25 UTC, Vyvy-vi commented on .github/workflows/community.yml
> +          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.eddiehub.org">Dis
```suggestion
          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.eddiehub.org">Discord server</a> and our <a href="http://github.eddiehub.org">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.''
```

2021-03-04 19:45 UTC, SashoStoichkov submitted a review, later dismissed
LGTM 👍🏻 If you make the changes @Vyvy-vi requested - it'll be ready for merge 😉

2021-03-05 16:00 UTC, SashoStoichkov approved these changes
LGTM 👍🏻 Great work everyone

2021-03-08 18:08 UTC, AllanRegush approved these changes
Looks Good :+1:

2021-03-08 18:11 UTC, merged

2021-03-08 21:37 UTC, SashoStoichkov commented
Thanks @AllanRegush 👍🏻